openapi: 3.0.3
info:
  title: Proagro facil API
  version: 1.0.0
  description: O Proagro Fácil é um sistema da Softfocus que facilita o gerenciamento
    de Proagro (Programa de Garantia da Atividade Agropecuária).
paths:
  /api/losses/:
    get:
      operationId: api_losses_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLossList'
          description: ''
    post:
      operationId: api_losses_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Loss'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Loss'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Loss'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Loss'
          description: ''
  /api/losses/{loss_id}/:
    get:
      operationId: api_losses_retrieve
      parameters:
      - in: path
        name: loss_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this loss.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Loss'
          description: ''
    put:
      operationId: api_losses_update
      parameters:
      - in: path
        name: loss_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this loss.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Loss'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Loss'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Loss'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Loss'
          description: ''
    patch:
      operationId: api_losses_partial_update
      parameters:
      - in: path
        name: loss_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this loss.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedLoss'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedLoss'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedLoss'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Loss'
          description: ''
    delete:
      operationId: api_losses_destroy
      parameters:
      - in: path
        name: loss_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this loss.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/losses/cpf/{cpf}/:
    get:
      operationId: api_losses_cpf_list
      parameters:
      - in: path
        name: cpf
        schema:
          type: string
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLossList'
          description: ''
components:
  schemas:
    EventTypeEnum:
      enum:
      - chuva excessiva
      - geada
      - granizo
      - seca
      - vendaval
      - raio
      - outro
      type: string
    Loss:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        first_name:
          type: string
          maxLength: 125
        last_name:
          type: string
          maxLength: 125
        email:
          type: string
          format: email
          maxLength: 255
        cpf:
          type: string
          maxLength: 11
        latitude:
          type: string
          maxLength: 14
        longitude:
          type: string
          maxLength: 14
        farming_type:
          type: string
          maxLength: 125
        harvest_date:
          type: string
          format: date
        event_type:
          $ref: '#/components/schemas/EventTypeEnum'
        create_at:
          type: string
          format: date-time
          readOnly: true
        update_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - cpf
      - create_at
      - email
      - farming_type
      - first_name
      - harvest_date
      - id
      - last_name
      - latitude
      - longitude
      - update_at
    PaginatedLossList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Loss'
    PatchedLoss:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        first_name:
          type: string
          maxLength: 125
        last_name:
          type: string
          maxLength: 125
        email:
          type: string
          format: email
          maxLength: 255
        cpf:
          type: string
          maxLength: 11
        latitude:
          type: string
          maxLength: 14
        longitude:
          type: string
          maxLength: 14
        farming_type:
          type: string
          maxLength: 125
        harvest_date:
          type: string
          format: date
        event_type:
          $ref: '#/components/schemas/EventTypeEnum'
        create_at:
          type: string
          format: date-time
          readOnly: true
        update_at:
          type: string
          format: date-time
          readOnly: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
