# Generated by Django 4.1 on 2022-08-25 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loss",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=125)),
                ("last_name", models.CharField(max_length=125)),
                ("email", models.EmailField(max_length=255)),
                ("cpf", models.CharField(max_length=11)),
                ("latitude", models.CharField(max_length=14)),
                ("longitude", models.CharField(max_length=14)),
                ("farming_type", models.CharField(max_length=125)),
                ("harvest_date", models.DateField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Chuva excessiva", "Chuva"),
                            ("Geada", "Geada"),
                            ("Granizo", "Granizo"),
                            ("Seca", "Seca"),
                            ("Vendaval", "Vendaval"),
                            ("Raio", "Raio"),
                            ("Outro", "Outro"),
                        ],
                        default="Outro",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
