# Generated by Django 4.1 on 2022-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("losses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loss",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("chuva excessiva", "Chuva"),
                    ("geada", "Geada"),
                    ("granizo", "Granizo"),
                    ("seca", "Seca"),
                    ("vendaval", "Vendaval"),
                    ("raio", "Raio"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
            ),
        ),
    ]
